[servers]
172.18.60.142


[servers:vars]
ansible_user=ansible-test
ansible_password=12345678
ansible_become=yes
ansible_become_method=sudo
ansible_become_password=12345678
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
